### PR TITLE
Turn off precompile

### PR DESCRIPTION
**Pull request by antoine-levitt**
Kill annoying warnings

### CODE REVIEW

**Comment by BioTurboNick** [comment]
Apart from avoiding precompilation, why does it prevent the warnings?

**Comment by antoine-levitt** [comment]
I would imagine the warnings are triggered by the precompilation?

**Comment by BioTurboNick** [comment]
Sure, but I'm curious why it's an issue. *shrugs*

**Comment by abcdvvvv** [comment]
However, I placed `using AbbreviatedStackTraces` in startup.jl. If you disable precompilation, I will receive a prompt about `? AbbreviatedStackTraces` every time I start Julia v1.12.1.

```
  ? AbbreviatedStackTraces
[ Info: Precompiling AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4]
┌ Info: Skipping precompilation due to precompilable error. Importing AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
  ? AbbreviatedStackTraces
[ Info: Precompiling AbbrvStackTracesREPLExt [e8b68d39-d898-5f3e-a788-3ac020247fe4]
┌ Info: Skipping precompilation due to precompilable error. Importing AbbrvStackTracesREPLExt [e8b68d39-d898-5f3e-a788-3ac020247fe4].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
```

**Comment by BioTurboNick** [comment]
@abcdvvvv please file a new issue if you have a problem, and please describe add more details.

**Pull request merged**
